import os

def rc4_keystream(key, length):
    S = list(range(256))
    j = 0
    key_bytes = [ord(c) for c in key]
    
    for i in range(256):
        j = (j + S[i] + key_bytes[i % len(key)]) % 256
        S[i], S[j] = S[j], S[i]
        
    i = j = 0
    keystream = []
    for _ in range(length):
        i = (i + 1) % 256
        j = (j + S[i]) % 256
        S[i], S[j] = S[j], S[i]
        keystream.append(S[(S[i] + S[j]) % 256])
    return keystream

def encrypt_bmp(input_filename, output_filename, key):
    print("=== Bitmap Image Encryption Visualizer (RC4) ===")
    
    if not os.path.exists(input_filename):
        print(f"[-] Error: Please place a file named '{input_filename}' in this folder.")
        return

    with open(input_filename, 'rb') as f:
        file_data = bytearray(f.read())

    header_size = 54
    header = file_data[:header_size]
    pixel_data = file_data[header_size:]

    print(f"[*] Loaded '{input_filename}' ({len(file_data)} bytes).")
    print(f"[*] Generating RC4 keystream for {len(pixel_data)} bytes of pixel data...")
    
    keystream = rc4_keystream(key, len(pixel_data))
    
    print("[*] Applying XOR encryption to pixels...")
    encrypted_pixels = bytearray([pixel ^ ks_byte for pixel, ks_byte in zip(pixel_data, keystream)])
    
    encrypted_file_data = header + encrypted_pixels

    with open(output_filename, 'wb') as f:
        f.write(encrypted_file_data)
        
    print(f"[+] Success! Encrypted image saved as '{output_filename}'.")
    print("[*] Open the encrypted image to view the visual static generated by RC4.")

encrypt_bmp('test_image.bmp', 'encrypted_image.bmp', 'SECURE_STREAM_KEY')